export enum envVariables {
  DIALECT = "DIALECT",
  STORAGE =  "STORAGE",
  NAME = "NAME",
  DADOS_USUARIO_TESTE_NOME = "DADOS_USUARIO_TESTE_NOME",
  DADOS_USUARIO_TESTE_EMAIL = "DADOS_USUARIO_TESTE_EMAIL",
  DADOS_USUARIO_TESTE_PASSWORD = "DADOS_USUARIO_TESTE_PASSWORD",
}
